name       : qt6-translations
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qttranslations-everywhere-src-6.2.2.tar.xz : fc9244224c6e9930035e7efc8b6b541c739aa4cccf46de9779bc3f64d8e94c8f
license    :
    - GFDL-3.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 Translation Components
description: |
    Translations Module for Qt6
builddeps  :
    - pkgconfig(Qt6UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
