name       : qt6-translations
version    : 6.5.1
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.5/6.5.1/submodules/qttranslations-everywhere-src-6.5.1.tar.xz : 527e2c34c2637ece49c0e1fb65b0c5e5dce0f9b3f3710381468fe4e36080d49b
license    :
    - GFDL-3.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 Translation Components
description: |
    Translations Module for Qt6
builddeps  :
    - pkgconfig(Qt6UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
