name       : qt6-translations
version    : 6.3.0
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qttranslations-everywhere-src-6.3.0.tar.xz : e4dd4ef892a34a9514a19238f189a33ed85c76f31dcad6599ced93b1e33440b3
license    :
    - GFDL-3.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 Translation Components
description: |
    Translations Module for Qt6
builddeps  :
    - pkgconfig(Qt6UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
