name       : qt6-translations
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qttranslations-everywhere-src-6.2.1.tar.xz : 3f680b520da585697fc725697a52c7d2074a6a728f6830366b491a6f8b9183c7
license    :
    - GFDL-3.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 Translation Components
description: |
    Translations Module for Qt6
builddeps  :
    - pkgconfig(Qt6UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
